services:
  db:
    image: postgres:14
    container_name: postgresql_database
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - app_network
  
  web:
    build: .
    container_name: django_backend
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env 
    volumes:
      - ./:/app
      - ./ufanet/media:/app/ufanet/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - app_network


volumes:
  postgres_data:

networks:
  app_network:
