services:
  db:
    image: postgres:14
    container_name: postgresql_database
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - app_network
  
  web:
    image: alexwhyhey/ufanet-partners-django:latest
    container_name: django_backend
    env_file: .env 
    volumes:
      - django:/var/lib/django/data
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network

volumes:
  postgres_data:
  django:

networks:
  app_network:
