# Generated by Django 5.2 on 2025-04-22 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('Region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('LogoPath', models.CharField(max_length=100)),
                ('About', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ButtonName', models.CharField(max_length=30)),
                ('WhatAboutOffer', models.CharField(max_length=30)),
                ('WhereToUse', models.CharField(max_length=50)),
                ('BackPhotoPath', models.CharField(max_length=150)),
                ('HowToGet', models.CharField(max_length=250)),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.categories')),
                ('CityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.cities')),
                ('PartnerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partners')),
            ],
        ),
    ]
